### ISSUE TITLE
Pending Approval

### ISSUE THREAD

**Issue by jasonseminara** [papersix/term#1]
I like it. What is your second model? Where will you be storing the photos? 

You can use the EXIF data on any image taken with a mobile phone. It should contain the GPS location and any info you'll need.

**Comment by papersix** [comment]
I was thinking of mongo's GridFS to store the images.  As i understand, this will store the images directly in the db --  but a better option may be to create a link & storing on an outside cdn -  any recco's on how to handle storage? 

 As with the models, I was thinking of using mongoose to setup a schema  for users- from there the  query the map, another to help with auth, and perhaps a  third to deal with other user / guest issues. I am still trying to grasp how this all fits together.  Hopefully at the end of today i will get a better idea of  what works.

**Comment by jasonseminara** [comment]
As we discussed, you should use Imgur to store your images
